# Використання базового образу з Node.js
FROM node:latest

# Встановлення робочого директорію у контейнері
WORKDIR /usr/src/app

# Копіювання package.json та package-lock.json (якщо існують)
COPY package*.json ./

# Встановлення залежностей проекту
RUN npm install

# Копіювання всіх файлів проекту у контейнер
COPY . .

# Відкриття порту 3000
EXPOSE 3000

# Команда для запуску вашого додатку
CMD ["npm", "run", "start"]
